name: This is demo workflow

on: [push]

jobs:

  npm install:
    name: This is npm install
    steps:
    - uses: actions/checkout
    - name: npm install
      run: npm i
    
  npm install2:
    steps:
    - uses: actions/checkout
    - name: npm install
      run: npm i 
    
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
